[package]
name = "sketchpad"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "30"
winit = "0.30"
pollster = "0.4"
env_logger = "0.10"
bytemuck = { version = "1", features = ["derive"] }
log = "0.4"
png = "0.18.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rfd = { version = "0.17.2", default-features = false, features = ["xdg-portal", "wayland"] }
egui = { git = "https://github.com/emilk/egui", rev = "2cb071f7f6d71e0f888ba31bec9b3eb5ed5428fe" }
egui-wgpu = { git = "https://github.com/emilk/egui", rev = "2cb071f7f6d71e0f888ba31bec9b3eb5ed5428fe", default-features = false }
egui-winit = { git = "https://github.com/emilk/egui", rev = "2cb071f7f6d71e0f888ba31bec9b3eb5ed5428fe", default-features = false, features = ["clipboard", "wayland", "x11"] }

[target.'cfg(target_os = "linux")'.dependencies]
raw-window-handle = "0.6"
x11rb = { version = "0.13", features = ["xinput"] }
